<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1639043297065' stop='1639043297474'>
    <name>Coding:</name>
    <title>Coding:</title>
    <test-cases>
        <test-case start='1639043297065' status='failed' stop='1639043297318'>
            <name>A warning message is displayed when a user tries to edit a data view script that is check out by another user and not released.</name>
            <title>A warning message is displayed when a user tries to edit a data view script that is check out by another user and not released.</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1639043297284' status='failed' stop='1639043297317'>
                    <name>I am on page "http://localhost/21_2_1_1_Designer/Account/LogOn"</name>
                    <title>I am on page "http://localhost/21_2_1_1_Designer/Account/LogOn"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments>
                <attachment title='Last Seen Screenshot' source='4613f84e-6372-4209-a705-fd6db11c5a55-attachment.png' type='image/png' size='7057'/>
            </attachments>
            <failure>
                <message>net::ERR_CONNECTION_REFUSED at http://localhost/21_2_1_1_Designer/Account/LogOn</message>
                <stack-trace>Error: net::ERR_CONNECTION_REFUSED at http://localhost/21_2_1_1_Designer/Account/LogOn
                    at navigate (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/FrameManager.js:96:23)
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                    at async FrameManager.navigateFrame (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/FrameManager.js:71:21)
                    at async Frame.goto (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/FrameManager.js:296:16)
                    at async Page.goto (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/Page.js:749:16)
                    at async Puppeteer.amOnPage (/home/davidbrudascu/puppeteer/puppeteer/node_modules/codeceptjs/lib/helper/Puppeteer.js:630:5)
                    at async Object.loginInStudioApp (/home/davidbrudascu/puppeteer/puppeteer/framework/actionDefinitions/commonActions.js:25:30)
                    at async Test.&lt;anonymous> (/home/davidbrudascu/puppeteer/puppeteer/ftosCore/testScenarios/coding/TC018_EditScriptDataViewWith2Users.js:24:3)
                  -- ASYNC --
                    at Frame.&lt;anonymous> (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
                    at Page.goto (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/Page.js:749:53)
                    at Page.&lt;anonymous> (/home/davidbrudascu/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/common/helper.js:110:27)
                    at Puppeteer.amOnPage (/home/davidbrudascu/puppeteer/puppeteer/node_modules/codeceptjs/lib/helper/Puppeteer.js:630:21)
                    at Step.run (/home/davidbrudascu/puppeteer/puppeteer/node_modules/codeceptjs/lib/step.js:122:47)
                    at /home/davidbrudascu/puppeteer/puppeteer/node_modules/codeceptjs/lib/actor.js:134:23</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>